services:
  postgres:
    image: postgres:15
    container_name: tasksmanager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskapp
      POSTGRES_PASSWORD: taskapp
      POSTGRES_DB: taskapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: