services:
  postgres:
    image: postgres:15
    container_name: tasksmanager-postgres
    restart: always
    environment:
      POSTGRES_USER: taskapp
      POSTGRES_PASSWORD: taskapp
      POSTGRES_DB: taskapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: